name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE: britedge-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & push image (latest)
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE }}:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE }}:latest

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: Brit
